name: my-infosec-awesome

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 3.0
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.2'
    - name: Build and test with awesome_bot
      run: |
        gem install awesome_bot
        awesome_bot README.md --white-list LICENSE,emailrep.io,dnsdumpster.com,"github.com/pe3zx/my-infosec-awesome/actions","tuts4you.com/download.php?list.17","ethtx.info" --allow-ssl --allow-redirect --allow 429
